# Generated by Django 5.2.17 on 2026-09-27 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('transfer_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_created', to=settings.AUTH_USER_MODEL)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='assets.equipmenttype')),
                ('from_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='assets.base')),
                ('to_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='assets.base')),
            ],
        ),
    ]
